services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - '6500:3306'
    volumes:
      - mysqlDB:/var/lib/mysql
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    container_name: phpMyAdmin
    env_file:
      - ./.env
    environment:
      - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
volumes:
  mysqlDB:
